// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using OtrsReportApp.Data;

namespace OtrsReportApp.Migrations.TicketDb
{
    [DbContext(typeof(TicketDbContext))]
    [Migration("20210224090219_TicketIdIntToLong")]
    partial class TicketIdIntToLong
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("OtrsReportApp.Models.OtrsTicket.AcknowledgedTicket", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<long>("TicketId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.ToTable("acknowledged_ticket");
                });
#pragma warning restore 612, 618
        }
    }
}
